# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('WEIGHT', 'WEIGHT'), ('FIXED', 'FIXED'), ('PRICE', 'PRICE')], default='FIXED', max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Open', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='date order group created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date order group created')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.PositiveIntegerField()),
                ('fulfillment_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_items', to='orders.FulfillmentGroup')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_order_items', to='catalog.Product')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems_sku_related', to='catalog.Sku')),
            ],
        ),
    ]
